name: MongoDB Query Profiler

on:
  pull_request:
    branches: [main]

jobs:
  profile-queries:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Extract MongoDB queries from PR
        run: node .github/scripts/extract-queries.js

      - name: Run MongoDB Profiler with extracted queries
        run: node .github/scripts/run-profiler.js

      - name: Analyze explain results
        run: node .github/scripts/analyze-explains.js

      - name: Upload profiler log
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mongodb-profiler-log
          path: .github/scripts/profiler-output.log

      - name: Read profiler output
        id: read_log
        run: |
          {
            echo "log_output<<EOF"
            cat .github/scripts/profiler-output.log
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Post profiler log to PR
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🧪 MongoDB Profiler Log Output
            ```
            ${{ steps.read_log.outputs.log_output }}
            ```
